# Generated by Django 4.2.5 on 2023-10-19 16:44

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customuser_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='type',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='coins',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userproducts',
            name='metal_quantity',
            field=models.JSONField(default=str),
        ),
        migrations.AddField(
            model_name='userproducts',
            name='product_image',
            field=models.ImageField(default='', upload_to=base.models.uploadproduct),
        ),
        migrations.AddField(
            model_name='userproducts',
            name='product_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Headset', 'Headset'), ('Laptop', 'Laptop'), ('Mixer', 'Mixer'), ('Refrigerator', 'Refrigerator'), ('Speaker', 'Speaker'), ('Television', 'Television'), ('Washing Machine', 'Washing Machine')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='condition',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Worst', 'Worst')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
