# Generated by Django 4.2.5 on 2023-10-19 19:02

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_userproducts_type_userproducts_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='coins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Worst', 'Worst')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='product_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=base.models.uploadproduct),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Headset', 'Headset'), ('Laptop', 'Laptop'), ('Mixer', 'Mixer'), ('Refrigerator', 'Refrigerator'), ('Speaker', 'Speaker'), ('Television', 'Television'), ('Washing Machine', 'Washing Machine')], default='', max_length=20, null=True),
        ),
    ]
