# Generated by Django 4.2.5 on 2023-10-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userproducts_approved_alter_userproducts_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
