# Generated by Django 4.2.5 on 2023-10-13 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_area_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_choices',
            field=models.TextField(blank=True, choices=[('employee', 'Employee'), ('sub_employee', 'Sub-employee'), ('baseUser', 'User')], null=True),
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=20)),
                ('manufacturer', models.CharField(default='', max_length=20)),
                ('model', models.CharField(default='', max_length=20)),
                ('condition', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
