# Generated by Django 4.2.5 on 2023-10-17 16:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_user_choices_userproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default='', upload_to=base.models.upload_to),
        ),
    ]
